### ISSUE TITLE
Fuzzy Highlighting has small graphical glitches

### ISSUE THREAD

**Issue by JimPix1** [bakkeby/dmenu-flexipatch#12]
I've noticed for a while now that the dmenu highlighting is a bit glitchy, specifically with certain letters, e.g:
![image](https://user-images.githubusercontent.com/79943327/165343617-fa82f69c-201c-4305-9e6c-0acda97fde34.png)
If you look carefully there is a blue line just before every highlighted M, which is weird.

**Comment by JimPix1** [comment]
I've noticed this in both the latest build and the build I use right now (From February the 3rd)
The patches I have are
alpha
- border
- center
- fuzzyhighlight
- fuzzymatch
- grid
- lineheight
- morecolor
- mousesupport
- numbers
- password
- restrict return
- color emoji

**Comment by bakkeby** [comment]
This seems to happen with the fuzzy highlight patch, but not the highlight patch.

**Comment by JimPix1** [comment]
Righto, issue renamed then :+1:

**Comment by bakkeby** [comment]
This only happens when lrpad is an odd number, i.e. it depends on the font and the font size. The issue has to do with deducting lrpad / 2 from the text width which means that the `x` variable ends up being positioned 1 pixel too far to the right when overwriting the text with the highlight.

**Comment by JimPix1** [comment]
So should I change the font size or?

**Comment by bakkeby** [comment]
With the above change it should look fine. I'd expect the original patch on the suckless site to have the same issue.

**Comment by JimPix1** [comment]
Ah, brilliant! It works perfectly now. Thanks Bakkeby :)
All that needs to be fixed now is #11 and I'll be able to update my dmenu-flexipatch build again
