### ISSUE TITLE
Highlight patch messes with multi-selection colouring

### ISSUE THREAD

**Issue by 62832** [bakkeby/dmenu-flexipatch#20]
I just noticed that when the highlight patch is applied and a search is being made, any entries added to a multi-selection only use the colours defined in `SchemeNorm` rather than the colours defined in `SchemeOut`. This also seems to happen irrespectively of the multi-selection patch.

An example of an entry normally added to a multi-selection, currently in orange
![image](https://user-images.githubusercontent.com/5098830/230939261-f0101dec-3d94-4714-b563-ff686857431c.png)

Whereas here, `st` is another selected entry but does not also show in orange during searching.
![image](https://user-images.githubusercontent.com/5098830/230939761-3241ffce-c012-4987-afb6-df885b89f246.png)
![image](https://user-images.githubusercontent.com/5098830/230939906-2661344e-f992-4551-b067-b9689d7deab5.png)

What might a potential fix for this look like or involve?

**Comment by 62832** [comment]
Doesn't seem to have much effect the way it's written. Same thing occurs.
![image](https://user-images.githubusercontent.com/5098830/231011425-ad1191ef-1f65-4f49-ac36-a69886a742ab.png)

**Comment by bakkeby** [comment]
Having given it a bit more thought I don't see how the highlighted parts of the match adds any relevant information to the table when the item anyway has been selected for output. I'll consider including the above.

**Comment by bakkeby** [comment]
Pushed the above, let me know if you experience any issues.

**Comment by 62832** [comment]
No issues here. Thanks a ton!
