### ISSUE TITLE
Can someone add my patch?

### ISSUE THREAD

**Issue by DarkSamus669** [bakkeby/dmenu-flexipatch#23]
I've created [caretwidth](https://github.com/DarkSamus669/dmenu-patches/blob/main/dmenu-caretwidth-5.2.diff) patch, but i don't know how to add it. I looked into source code of flexipatch and it's scary.

**Comment by bakkeby** [comment]
Done. I wonder what kind of workflow you have that makes you need to change the width of the caret.

I suppose setting the caret width to 0 or -5 are the most interesting options.
