### ISSUE TITLE
Patch manpage as well

### ISSUE THREAD

**Issue by MithicSpirit** [bakkeby/dmenu-flexipatch#6]
I presume this isn't possible with the current system, but it'd be nice if it was possible to also patch the `dmenu.1` manpage (maybe there's something weird that can be done with the preprocessor?). A possible alternative would be to include all settings for all patches in the manpage by default, along with a message in each saying that it's only available if that patch was enabled.

**Comment by bakkeby** [comment]
Yes I think you would need a custom preprocessor script to do something like that.

I have always considered the manpages to be out of scope given the general aim of these projects being to allow users to try patches out before committing to including them in their own personal builds.

**Comment by JimPix1** [comment]
Another thing to note is that not every patch patches ``dmenu.1`` either, a lot of patches don't bother changing the manpage and instead just change the ``-h`` output
